// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.robot.subsystems;

import org.usfirst.frc4930.robot.Robot;
import org.usfirst.frc4930.robot.RobotMap;
import org.usfirst.frc4930.robot.commands.*;

import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon talonSRXLeftBack1 = RobotMap.driveTrainTalonSRXLeftBack1;
    private final CANTalon talonSRXLeftFront2 = RobotMap.driveTrainTalonSRXLeftFront2;
    private final CANTalon talonSRXRightBack3 = RobotMap.driveTrainTalonSRXRightBack3;
    private final CANTalon talonSRXRightFront4 = RobotMap.driveTrainTalonSRXRightFront4;
    private final RobotDrive robotDrive = RobotMap.driveTrainRobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TankDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    public void tankDrive(Joystick left, Joystick right){
    	robotDrive.tankDrive( left, right );
    }
    public void takeJoystickInputs(Joystick left, Joystick right) {
	
    	if(RobotMap.isButton3pressed == true){
    		robotDrive.tankDrive(-left.getY(), -right.getY());
       	}
       	else {
       		robotDrive.tankDrive(left.getY(), right.getY());
        }
    	
    	
	}
    public void stop(){
    	robotDrive.drive(0, 0);
    }
}

