// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.DanceBot2016;

import org.usfirst.frc4930.DanceBot2016.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;

import org.usfirst.frc4930.DanceBot2016.subsystems.*;
import org.usfirst.frc4930.DanceBot2016.commands.AutonomousCommand;

/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    public Joystick joystick0;
    public Joystick joystick1;
    public static JoystickButton button3;
    public static JoystickButton button4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        joystick1 = new Joystick(1);
        
        joystick0 = new Joystick(0);
        
        button3 = new JoystickButton(joystick0, 3);
        button4 = new JoystickButton(joystick0, 4);
        
        
        button3.whenPressed(new SwitchCams());
        button4.whenPressed(new SwitchCams());
        
//        if(button3.get()){
//        	Robot.button3IsPressed = !Robot.button3IsPressed;
//        }
//        if(button4.get()){
//        	Robot.button4IsPressed = !Robot.button4IsPressed;
//        }


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());
        SmartDashboard.putData("TankDrive", new TankDrive());

        //SmartDashboard.putString("Left DriveTrain Encoder Data: ", TankDrive.leftEncoderDistance);
        //SmartDashboard.putString("Right DriveTrain Encoder Data: ", TankDrive.leftEncoderDistance);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick0() {
        return joystick0;
    }

    public Joystick getJoystick1() {
        return joystick1;
    }
    public JoystickButton getButton3(){
    	return button3;
    }
    public JoystickButton getButton4(){
    	return button4;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

