// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.DanceBot2016;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc4930.DanceBot2016.commands.*;
import org.usfirst.frc4930.DanceBot2016.subsystems.*;

import com.ni.vision.NIVision;
import com.ni.vision.NIVision.Image;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    //int session;
    //Image frame;
     
    //CameraServer server2;
    
	
	Command autonomousCommand;
//	public static boolean button3IsPressed = false;
//	public static boolean button4IsPressed = false;
    public static OI oi;
    public static Cameras Cameras;
    public static DriveTrain driveTrain;
    

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    RobotMap.init();

        driveTrain = new DriveTrain();
        
        Cameras = new Cameras();
        
//        server2 = CameraServer.getInstance();
//        server2.setQuality(50);
//        server2.startAutomaticCapture("cam0");
         

        
        oi = new OI();



        autonomousCommand = new AutonomousCommand();

//        frame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_RGB, 0);
//        session = NIVision.IMAQdxOpenCamera("cam0",
//         		NIVision.IMAQdxCameraControlMode.CameraControlModeController);
//        NIVision.IMAQdxConfigureGrab(session);

    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){

    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
        if (autonomousCommand != null) autonomousCommand.start();
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {

        if (autonomousCommand != null){
        	autonomousCommand.cancel();
        }
        Cameras.initialize();
        //NIVision.IMAQdxStartAcquisition(session);
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        Cameras.execute();
//        NIVision.IMAQdxGrab(session, frame, 1);
//        CameraServer.getInstance().setImage(frame);
    }


    public void testPeriodic() {
        LiveWindow.run();
    }
//    public boolean getButton3(){
//    	return button3IsPressed;
//    }
}
