// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4930.robot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.CANTalon.TalonControlMode;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainTalonSRXLeftBack1;
    public static CANTalon driveTrainTalonSRXLeftFront2;
    public static CANTalon driveTrainTalonSRXRightBack3;
    public static CANTalon driveTrainTalonSRXRightFront4;
    public static RobotDrive driveTrainRobotDrive;
    public static boolean isButton3pressed = false;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainTalonSRXLeftBack1 = new CANTalon(0);
        LiveWindow.addActuator("DriveTrain", "TalonSRXLeftBack1", driveTrainTalonSRXLeftBack1);
        
        driveTrainTalonSRXLeftFront2 = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "TalonSRXLeftFront2", driveTrainTalonSRXLeftFront2);
        
        driveTrainTalonSRXRightBack3 = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "TalonSRXRightBack3", driveTrainTalonSRXRightBack3);
        
        driveTrainTalonSRXRightFront4 = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "TalonSRXRightFront4", driveTrainTalonSRXRightFront4);
        
        driveTrainRobotDrive = new RobotDrive( driveTrainTalonSRXLeftBack1, driveTrainTalonSRXLeftFront2, driveTrainTalonSRXRightBack3, driveTrainTalonSRXRightFront4 );
        
        driveTrainRobotDrive.setSafetyEnabled(true);
        driveTrainRobotDrive.setExpiration(0.1);
        driveTrainRobotDrive.setSensitivity(0.5);
        driveTrainRobotDrive.setMaxOutput(1.0);
        
        driveTrainTalonSRXLeftBack1.changeControlMode(TalonControlMode.Follower);
        driveTrainTalonSRXLeftBack1.set(driveTrainTalonSRXLeftFront2.getDeviceID());
        
        driveTrainTalonSRXRightBack3.changeControlMode(TalonControlMode.Follower);
        driveTrainTalonSRXRightBack3.set(driveTrainTalonSRXRightFront4.getDeviceID());
                
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
